#pragma once

#define DEBUG

#define CHUNKSIZE 0x100
#define IORING_CHUNK_SIZE 0x130

#define MAX_TRIES_PER_LEAK 1000

#define THREADNAME_THREAD_COUNT 256
#define THREADNAME_MAX_USES_PER_LEAK 256
#define THREADNAME_OVERFLOW_SETTLE_MS 3

#define OVERFLOW_IRP_WAIT_MS 120
#define OVERFLOW_IRP_SECOND_WAIT_MS 80

#define CORRUPT_PIPE_ATTEMPTS 2
